apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-training-job
spec:
  template:
    spec:
      containers:
      - name: training-container
        image: srush98/trainmnistrnn:latest
        volumeMounts:
        - mountPath: "/model"
          name: model-volume
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: mnist-model-pvc
      restartPolicy: Never